Numpy
=
- numerical python
- used for working with arrays
- created in 2005 by travis oliphant
- list serves the purpose of arrays but they are slow to process
- numpy provide array obj that is upto 50x faster then tradition python lists

In [2]:
import numpy as np
import sys

#list
s=range(1000)
print('size of each element of list in bytes ', sys.getsizeof(s))
print('size of whole list in bytes ', sys.getsizeof(s)*len(s))

#numpy array
D=np.arange(1000)
print('size of each element of numpy array in bytes ', D.itemsize)
print('size of whole numpy array in bytes ', D.itemsize*D.size)

size of each element of list in bytes  48
size of whole list in bytes  48000
size of each element of numpy array in bytes  4
size of whole numpy array in bytes  4000


In [31]:
import numpy as np
arr=np.array(42)
print(arr)
print(arr.ndim) #dimension-0
print(type(arr))
print()

arr=np.array([1,2,3,4,5])
print(arr)
print(arr.ndim) #dimension-1
print(type(arr))
print()

arr=np.array([[1,2,3,4,5]])
print(arr)
print(arr.ndim) #dimension-2
print(type(arr))
print()

arr=np.array([[[1,2,3,4,5]]])
print(arr)
print(arr.ndim) #dimension-3
print(type(arr))
print()

arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.ndim) #dimension
print(type(arr))
print()

arr=np.array([1,2,3,4,5])
print(arr)
print(arr[3])
#print(arr[5]) IndexError
print(arr[3]+arr[4]) # 4+5=9
print()

arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1[0,1])  # arr1[0][1]
print(arr1[1,1])
print(arr1[0,3])
print(arr1[1,2])
print()

arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])
print(arr[1,1,1])
print(arr[0,0,1])
print(arr[1,0,2])
print(arr[1,1,2])
print(arr[0:2,0:2,0:2]) #[[[ 1  2][ 4  5]][[ 7  8][10 11]]]
print(arr[0:2,0:2,2])
print(arr[0:2,1,0:2])
print(arr[0:2,1:2,0:2])
print(arr[0:2,1,2])
print()

arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,-1])
print(arr[1,0:3])
print(arr[0:2,2])
print()

arr=np.array([1,2,3,4,5])
print(arr[1:3])
print(arr[1:])
print(arr[1:2])
print(arr[0:5:2])
print(arr[-3:-1])
print(arr[::-1])

42
0
<class 'numpy.ndarray'>

[1 2 3 4 5]
1
<class 'numpy.ndarray'>

[[1 2 3 4 5]]
2
<class 'numpy.ndarray'>

[[[1 2 3 4 5]]]
3
<class 'numpy.ndarray'>

[[1 2 3 4]
 [5 6 7 8]]
2
<class 'numpy.ndarray'>

[1 2 3 4 5]
4
9

2
6
4
7

6
11
2
9
12
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]
[[ 3  6]
 [ 9 12]]
[[ 4  5]
 [10 11]]
[[[ 4  5]]

 [[10 11]]]
[ 6 12]

8
[5 6 7]
[3 7]

[2 3]
[2 3 4 5]
[2]
[1 3 5]
[3 4]
[5 4 3 2 1]


In [34]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr1.ndim)
print(arr1.shape)
print()
print(arr2.ndim)
print(arr2.shape)
print()
print(arr3.ndim)
print(arr3.shape)

1
(5,)

2
(2, 4)

3
(2, 2, 3)


In [49]:
import numpy as np
arr1=np.array([1,2,3,4,5,6],ndmin=5)
print(arr1)
print(arr1.shape)
print(arr1.ndim)
print()

arr=arr1.reshape(2,3)
print(arr)
print()

arr=arr1.reshape(3,2)
print(arr)
print()

arr=arr1.reshape(1,1,6)
print(arr)
print()

arr=arr1.reshape(1,2,3)
print(arr)
print()

arr=arr1.reshape(3,2).base
print(arr) #original array before reshape
print()

arr=arr1.reshape(2,-1) #-1=3
print(arr)
print()

arr=arr1.reshape(3,-1) #-1=2
print(arr)

[[[[[1 2 3 4 5 6]]]]]
(1, 1, 1, 1, 6)
5

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]

[[[1 2 3 4 5 6]]]

[[[1 2 3]
  [4 5 6]]]

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]


Iteration
=

In [59]:
import numpy as np
arr=np.array([1,2,3,4,5])
for i in arr:
    print(i,end=" ")
print()

arr=np.array([[1,2,3,4],[5,6,7,8]])
for i in arr:
    for j in i:
        print(j,end=" ")
print()

arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np.nditer(arr):
    print(x,end=" ")
print()

arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[0:1,::2]):
    print(x,end=" ")
print()
for x in np.nditer(arr[:,::2]):
    print(x,end=" ")

1 2 3 4 5 
1 2 3 4 5 6 7 8 
1 2 3 4 5 6 7 8 9 10 11 12 
1 3 
1 3 5 7 

Concatenate
=

In [67]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr=np.concatenate((arr1,arr2,arr3))
print(arr)
arr=np.concatenate((arr1,arr2,arr3),axis=0)
print(arr)
arr=np.concatenate((arr1,arr2,arr3),axis=1)
print(arr)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


AxisError: axis 1 is out of bounds for array of dimension 1

In [77]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)
print(arr.shape)
print()
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)
print(arr.shape)

[[1 2 5 6]
 [3 4 7 8]]
(2, 4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


Split
=

In [86]:
import numpy as np
arr1=np.array([1,2,3,4])
a=np.array_split(arr1,4)
print(a)
print()
a=np.array_split(arr1,3)
print(a)
print()
a=np.array_split(arr1,2)
print(a)
print()
arr=np.array([[1,2],[3,4],[5,6],[7,8]])
a=np.array_split(arr,4)
print(a)
print()
a=np.array_split(arr,4,axis=0)
print(a)
print()
a=np.array_split(arr,4,axis=1)
print(a)
print()
a=np.array_split(arr,6,axis=0)
print(a)

[array([1]), array([2]), array([3]), array([4])]

[array([1, 2]), array([3]), array([4])]

[array([1, 2]), array([3, 4])]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int32)]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]]), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32)]


Where
=

In [90]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,4,3,2])
x=np.where(arr1==4)
print(x)
print()
x=np.where(arr1%2==0)
print(x)
print()
arr1=np.array([[1,2],[3,4],[4,5],[7,8]])
x=np.where(arr1==4)
print(x)

(array([3, 6], dtype=int64),)

(array([1, 3, 5, 6, 8], dtype=int64),)

(array([1, 2], dtype=int64), array([1, 0], dtype=int64))


Sort
=

In [16]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,4])
print(np.sort(arr1))
print()

arr2=np.array([True,False,True])
print(np.sort(arr2))
print()

arr3=np.array([[3,4,2],[1,7,3],[4,2,5]])
print(np.sort(arr3))
print()
print(np.sort(arr3,axis=1))
print()
print(np.sort(arr3,axis=0))
print()

arr4=np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,6,4]]])
print(np.sort(arr4))
print()
print()
print(np.sort(arr4,axis=2))
print()
print()
print(np.sort(arr4,axis=0))
print()
print()
print(np.sort(arr4,axis=1))
print()
print()

[1 2 3 4 4 5 6]

[False  True  True]

[[2 3 4]
 [1 3 7]
 [2 4 5]]

[[2 3 4]
 [1 3 7]
 [2 4 5]]

[[1 2 2]
 [3 4 3]
 [4 7 5]]

[[[2 3 8]
  [3 7 9]]

 [[2 6 7]
  [4 6 9]]]


[[[2 3 8]
  [3 7 9]]

 [[2 6 7]
  [4 6 9]]]


[[[3 2 2]
  [7 6 3]]

 [[6 7 8]
  [9 9 4]]]


[[[3 2 3]
  [7 9 8]]

 [[6 6 2]
  [9 7 4]]]


